pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    
    //time setup
    //one job is running two builds at a time we use concurrnce
    // colours enable
    options {
       // timeout(time:1, unit: 'HOURS')
        // disableConcurrentBuilds()
        ansiColor('xterm')
    } 
    // accesing this value we can connect pipeline
    // accept the parameter variables is required
    
    //build
    stages {
        stage('init') {
            steps {
                sh """
                cd 01-vpc
                terraform init -reconfigure
                """
            }
        }
        stage('plan') {
            steps {
                sh """
                cd 01-vpc
                terraform plan
                """
            }
        }
        // after aplying environment we can use shell script
        stage('Deploy') {
            when {
                expression { 
                    params.action == 'apply'
                }
            }
            input {
                message "Should we continue?"
                ok "Yes, we should."
                
            }
            steps {
                sh """
                    cd 01-vpc
                    terraform apply -auto-approve
                """
            }
        }
        // after adding first commit we won't get nexr commit we will get
         stage('Destroy') {
            when {
                expression { 
                    params.action == 'destroy'
                }
            }
            input {
                message "Should we continue?"
                ok "Yes, we should."
                // submitter "alice,bob"
                // parameters {
                //     string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                // }
            }
            steps {
                sh """
                    cd 01-vpc
                    terraform destroy -auto-approve
                """
            }
        }
    }
     parameters {
        choice(name: 'action', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    // post buld
    post {
        always {
            echo 'Hai Hello'
        }
        failure {
            echo 'pipeline s failed'
        }
        success {
            echo 'pipeline success'
        }
    }
}